### ISSUE TITLE
confint.Deriv not called in derivFun.R

### ISSUE THREAD

**Issue by trashbirdecology** [gavinsimpson/random_code#1]
In derivFun.R you never call confint.Deriv. Instead, you call `stats::confint`:

`CI <- confint(m2.d, alpha = 0.01)`

Not sure if this was purposeful. [Same goes for the blogpost](https://www.fromthebottomoftheheap.net/2011/06/12/additive-modelling-and-the-hadcrut3v-global-mean-temperature-series/)

**Comment by gavinsimpson** [comment]
Thanks, but I think this is working as it should. `derivFun.R` is not running anything, just setting up the functions, which do end up being called in the blog post you linked to.

`m2.d` is an object of class `Deriv` so S3 dispatch should be calling `confint.Deriv()`.

This stuff is also getting pretty ancient; the code in the [*gratia*](gavinsimpson/gratia) package is more up-to-date and maintained.

**Comment by trashbirdecology** [comment]
Thanks for letting me know about gratia.....your few blog posts on gams are still alive and doing well, perhaps you could make reference to gratia at the top of them ?
